Google GitHub
T00lio/quiz pull request #13
Opened 2024-03-18 04:14 UTC by T00lio

Card Link: https://trello.com/c/5xNfK91M

1. installed Auth0 for google sign in functionality
2. created google button component
3. created profile page and component for display of user info

2024-03-18 13:58 UTC, brianmontero18 requested changes
No puedo probar el branch en mi local porque me salen estos errores

<img width="914" alt="image" src="https://github.com/T00lio/quiz/assets/11441487/aee9d37b-bf4f-47cd-8e52-5b992f6c3f30">

parece que hay un problema al importar los componentes. Te puedes fijar en la forma como los estas importando/exportando?

2024-03-18 13:58 UTC, brianmontero18 commented on client/.gitignore
> -.env
los archivos `.env` deben estar en el `.gitignore` porque no queremos exponer las claves por temas de seguridad.
Lo que se suele subir es un archivo `.env.template` que es como un placeholder de las variables. Luego, de forma privada, se comparten estas variables por otros medios con el resto del equipo.

puedes leer:
https://www.getfishtank.com/blog/best-practices-for-committing-env-files-to-version-control
<img width="671" alt="image" src="https://github.com/T00lio/quiz/assets/11441487/f2a9df6b-5ed4-4f3e-9586-8d078eab36c6">

2024-03-18 13:58 UTC, brianmontero18 commented on client/src/components/ContactForm/ContactFrom.jsx
> +function ContactFrom() {
typo issue:
ContactFrom should be ContactForm

2024-03-18 13:58 UTC, brianmontero18 commented on client/src/components/ContactForm/ContactFrom.jsx
> +import { TELEPHONE, PORTFOLIO_URL } from "../../global const/index";
te recomendaria que nunca coloques espacios para nombrar archivos, carpetas, etc porque suele generar problemas dependiendo del sistema operativo. Aunque la mayoria de los sistemas modernos pueden manejarlos, es una practica comun evitarlos para asegurar la compatibilidad con diferentes entornos.

En su lugar, se suelen utilizar convenciones como camelCase, snake_case o kebab-case para separar palabras en los nombres de archivos y carpetas

2024-03-18 13:58 UTC, brianmontero18 commented on client/src/components/footer/index.js
> +export { default } from "../Footer/Footer.jsx";
it should be `export { default } from "./footer.jsx";`

2024-03-18 13:58 UTC, brianmontero18 commented on client/src/pages/Signin.jsx
>  export default function Signin() {
tiny thing:
al ser 2 palabras y si usamos la convencion camelCase it should be `SignIn`

2024-03-18 13:58 UTC, brianmontero18 commented on client/src/pages/Singup.jsx
>  export default function Singup() {
SignUp

2024-03-18 13:58 UTC, brianmontero18 commented on client/src/pages/Singup.jsx
> +import React, { useState } from "react";
not necessary to import React default object anymore since React 16

2024-03-20 22:29 UTC, T00lio reviewed
Worked on comments provide on initial review.

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/.gitignore
> -.env
.en added to .gitignore file

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/src/pages/Singup.jsx
>  export default function Singup() {
Function name updated

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/src/pages/Singup.jsx
> +import React, { useState } from "react";
Will consider from now on

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/src/pages/Signin.jsx
>  export default function Signin() {
Update to camel case

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/src/components/footer/index.js
> +export { default } from "../Footer/Footer.jsx";
updated to reuested format

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/src/components/ContactForm/ContactFrom.jsx
> +import { TELEPHONE, PORTFOLIO_URL } from "../../global const/index";
Noted!

2024-03-20 22:29 UTC, tulio-salvatierra commented on client/src/components/ContactForm/ContactFrom.jsx
> +function ContactFrom() {
Updated

2024-03-21 01:53 UTC, T00lio commented
ready to merge

2024-04-19 14:55 UTC, brianmontero18 approved these changes

2024-04-19 14:56 UTC, merged