Add mock data
T00lio/quiz pull request #17
Opened 2024-04-23 13:10 UTC by T00lio

Added mock data to showcase quiz functionality

modified useEffect on quizPage to use mock data and success component to work accordingly

2024-04-25 15:35 UTC, brianmontero18 requested changes

2024-04-25 15:35 UTC, brianmontero18 commented on client/src/components/success/Success.jsx
> +function SuccessSection({ score, handleRestart, questions }) {
`questions` no se termina usando en este componente, asi que puedes quitarlo, que te parece?

2024-04-25 15:35 UTC, brianmontero18 commented on client/src/components/success/Success.jsx
> +        You scored {score} out of 5.
el numero 5 esta harcodeado pero bien puede ser un valor dinamico que puede ser `totalQuestions` o simplemente `total` y que vendria a representar el total de preguntas.. 
logicamente es totalmente configurable puede ser 5, 10, 15, 100. EL componente no le interesa cuantas son. El simplemente cumple su responsabilidad de mostrar un mensaje de Success, se entiende la idea?

2024-04-25 16:07 UTC, brianmontero18 commented
Solucionar bug, explicado aca:
https://www.loom.com/share/a0a9da96f99c4d989609c21d20073e61?sid=4b261b75-bfc1-46f9-80a3-674eabf0b95f

2024-04-26 01:15 UTC, T00lio commented on client/src/components/success/Success.jsx
> +function SuccessSection({ score, handleRestart, questions }) {
Esto lo pase precisamente para hacer display del numero de preguntas en vez de hard codearlas pero lo deje, ya que lo estaba pasando del padre (quiz) pero lo vamos a sacar y cuanto se hagan los llamados completos desde el back end lo coloco dinamico

2024-07-03 01:24 UTC, T00lio commented on client/src/components/success/Success.jsx
> +        You scored {score} out of 5.
this was done dynamically passing score and questions.length into component

2024-07-03 01:24 UTC, T00lio commented
Branch merge

2024-07-03 01:24 UTC, T00lio commented
branch merged

2024-07-03 01:24 UTC, closed without merging