Ts install
T00lio/quiz pull request #18
Opened 2024-04-24 02:19 UTC by T00lio

Migrate files and components to typescript

Trello Cards: 
[Trello](https://trello.com/c/SPTLx4Kk)
[Trello](https://trello.com/c/5qzkjcaA)

Agregar typescript al proyecto existente. Solo incluye instalar dependencias y configuracion del proyecto

2024-04-25 15:01 UTC, brianmontero18 requested changes

2024-04-25 15:01 UTC, brianmontero18 commented on client/package.json
>      "tailwindcss": "^3.0.7"
cuando hago voy a probar en mi local tu branch lo primero que hago es actualizar las dependencia (npm install) y me sale este error:

![image](https://github.com/T00lio/quiz/assets/11441487/45e2123c-069b-4f93-a7e5-6c57fca36054)


investigando un poco,  parece que hay un conflicto en las dependencias relacionado con la version de TypeScript requerida por `react-scripts`.
Por lo que veo `react-scripts` requiere TypeScript en la versión ^3.2.1 || ^4 (es lo que observo en el arbol de dependencia de react-scripts cuando me fijo en el `package-lock.json`), mientras que tienes TypeScript en la versión ^5.4.5 (segun tu package.json).

Esto es un buen momento para observar la importancia del `package-lock.json` y la diferencia que tiene con `package.json`:

* `package.json`: Este archivo se utiliza para definir las dependencias del proyecto y sus rangos de versiones. Es como una lista de las herramientas que necesitas para construir algo, pero no necesariamente especifica las versiones exactas. Por ejemplo, podrías decir que necesitas una biblioteca llamada "lodash" en cualquier versión mayor o igual a la 4.0.0.

 * `package-lock.json`: Este archivo es más detallado y específico. Se genera automáticamente cuando ejecutas npm install y registra la versión exacta de cada dependencia instalada. Incluso registra las dependencias de tus dependencias (es decir, las dependencias transitivas) y sus versiones exactas. Esto garantiza que, al instalar el proyecto en otra máquina o en un entorno de producción, obtendrás exactamente las mismas versiones de las dependencias, lo que garantiza que el proyecto sea consistente y reproducible.

En resumen, `package.json` especifica qué necesitas, mientras que `package-lock.json` detalla exactamente qué se instaló, incluidas las versiones exactas de todas las dependencias.


Como los de create-react-app ya no estan dando mas mantenimiento desde hace 2 anios, entonces es muy probable que este conflicto y muchos mas existan a medida que vayamos queriendo utilizar versiones nuevas de Typescript o de cualquiera otra libreria... 

Un workaround que ellos mismos proponen es este:
https://github.com/facebook/create-react-app/issues/13080#issuecomment-1487975896

2024-04-25 15:01 UTC, brianmontero18 commented on client/tsconfig.json
> +    "jsx": "react" /* Specify what JSX code is generated. */,
aca tienes que cambiarlo por:
``
    "jsx": "react-jsx"
``
Al especificar `"jsx": "react-jsx"`, le estás indicando al compilador de TypeScript que debe reconocer y procesar la sintaxis JSX de manera similar a como lo haría en un proyecto de React con JavaScript estándar. Esto es crucial para que TypeScript pueda compilar correctamente tus archivos de React que contienen JSX.

De esta manera evitas colocar `import React 'from 'react';` en todos los archivos tsx

2024-04-25 15:01 UTC, brianmontero18 commented on client/src/App.tsx
> +import React from "react";
No es necesario agregar `import React from "react";` en todos los archivos tsx

Chequear el comentario que hice en el archivo `tsconfig.json`

2024-04-25 15:01 UTC, brianmontero18 commented on client/src/components/ContactForm/ContactForm.tsx
> +import React from "react";
No es necesario agregar `import React from "react";` en todos los archivos tsx

Chequear el comentario que hice en el archivo `tsconfig.json`

2024-04-25 15:01 UTC, brianmontero18 commented on client/src/components/GoogleLogoutButton/index.ys
ojo aca...
index.ys --->index.ts

2024-04-25 15:01 UTC, brianmontero18 commented on client/src/pages/QuizPage.tsx
> +
esto colocalo por fuera del componente, generalmente arriba despues de los imports y antes de `function QuizComponent() {`

2024-04-26 02:08 UTC, T00lio commented on client/package.json
>      "tailwindcss": "^3.0.7"
override added in package.json, pero el error no lo tengo en mi maquina.

2024-04-26 02:10 UTC, T00lio commented on client/tsconfig.json
> +    "jsx": "react" /* Specify what JSX code is generated. */,
updated as requested

2024-04-26 02:10 UTC, T00lio commented on client/src/components/ContactForm/ContactForm.tsx
> +import React from "react";
Removed from all files

2024-04-26 02:11 UTC, T00lio commented on client/src/components/ContactForm/ContactForm.tsx
> +import React from "react";
updated accordingly

2024-04-26 02:19 UTC, T00lio commented on client/src/pages/QuizPage.tsx
> +
updated!

2024-04-26 02:20 UTC, T00lio commented on client/src/App.tsx
> +import React from "react";
Borrado de todos los componentes y añadido el workaround señalado

2024-04-26 13:03 UTC, brianmontero18 approved these changes

2024-04-26 13:10 UTC, merged